### ISSUE TITLE
Aviso al momento de seleccionar el archivo CSV

### ISSUE THREAD

**Issue by delcabo** [caom92/qc-score-card#1]
Manda un mensaje de error de archivo!, para primera prueba, estoy usando el archivo que enviaste de SKYPE

![image](https://user-images.githubusercontent.com/28766240/32564514-58ce13a4-c469-11e7-8714-75a95067eb70.png)

**Comment by caom92** [comment]
Revise el contenido del archivo con Notepad o con Excel, es posible que se haya corrompido al descargarlo. Yo he usado ese mismo archivo para hacer pruebas en su servidor y no he tenido problemas con ello.
