### ISSUE TITLE
productos solo por la zona que seleccione

### ISSUE THREAD

**Issue by delcabo** [caom92/qc-score-card#4]
apoco seria MUY dificil si solo aparecen las opciones que producto que tenga la ZONA seleccionada?

![image](https://user-images.githubusercontent.com/28766240/32972686-679a2aa8-cba8-11e7-8f73-a25867d9e005.png)

**Comment by caom92** [comment]
De hecho si, porque el archivo CSV me da muy pocas herramientas con las cuales trabajar, tendría que visitar los ~20K registros cada vez que selecciona una zona solamente para descartar aquellos renglones que contienen información que no corresponde a esa zona al mismo tiempo que ignoro aquellos registros que tengan un producto que ya conté. Luego es pasar la lista resultante al combo box de un costado, pero no sin antes borrar la lista ahí almacenada. 

Si desea puedo implementarlo, pero dependiendo de la cantidad de datos que se encuentren almacenados en el archivo y de la velocidad de su dispositivo, puede haber ocasiones donde tarde mucho en cargar la nueva lista de productos que corresponden únicamente a la zona elegida.

**Comment by caom92** [comment]
Ya lo agregue
