### ISSUE TITLE
Reporte se brinco a otra hoja!

### ISSUE THREAD

**Issue by delcabo** [caom92/qc-score-card#5]
por lo pronto se puede hacer estas 4 graficas en 1 hoja completa!?

![image](https://user-images.githubusercontent.com/28766240/33350281-d1c453e2-d452-11e7-9497-5628cf193760.png)

**Comment by caom92** [comment]
Ya quedó arreglado, el problema era la fecha, si se fija se imprimía en un formato incorrecto y eso hacía que el encabezado quedara en 2 renglones, por eso las gráficas se saltaban a la siguiente página. 

![screenshot_2017-12-01_11-59-21](https://user-images.githubusercontent.com/9997614/33500850-3d8dd8f8-d68f-11e7-97e5-d173adc79369.png)
