### ISSUE TITLE
password! a la pagina

### ISSUE THREAD

**Issue by delcabo** [caom92/qc-score-card#7]
Ponerle password al entrar a este link,,,

http://score.jfdc.tech/#/

Solo nivel Director que pueda entrar!!

O tal vez tienes otro idea mejor!!

**Comment by caom92** [comment]
Idealmente es unificar todos los sistemas que tenemos para que con hacer inicio de sesión 1 vez se pueda tener un control de acceso a los diferentes componentes del sistema basado en el rol que tenga cada usuario, pero por ahora se puede hacer lo mismo que se hizo con Document Manager; agregar un enlace que te lleve a la página y que sólo sea accesible para el Director. Hacer esto sin embargo no limita el acceso a otros usuarios que **no** tengan el rol de Director; cualquier persona que tenga el link a la página podrá acceder a ella, pero es la solución más rápida que puedo ofrecer.

**Comment by caom92** [comment]
Terminé agregando un enlace que sólo el director puede ver que lo redirige a esa página (pero la página en sí, no restringe el acceso de otros usuarios). El enlace quedará visible para la versión 2.
